### PR TITLE
Resave newly fetched version of element in EVENT_AFTER_SAVE_ELEMENT

### PR DESCRIPTION
**Pull request by monachilada**
Further fixes for https://github.com/besteadfast/craft-preparse-field/issues/64 and potentially also https://github.com/besteadfast/craft-preparse-field/issues/62

The fix @brandonkelly submitted [here](https://github.com/besteadfast/craft-preparse-field/pull/65) worked for elements that already existed, but some funky behaviour stripping matrix fields still occurred the first time an element was created.

This PR attempts to fix that, by ensuring that the element being resaved in the `EVENT_AFTER_SAVE_ELEMENT` is a freshly fetched version of itself, rather than the version of the element that was passed through the event. This way, matrix references appear to correctly match up and thus are correctly saved alongside the preparse data that is generated.

Also some minor formatting occurred, sorry that the diff is a little difficult to follow.

### CODE REVIEW

**Comment by monachilada** [comment]
@jalendport @rjhewitt3 Hi folks, happy new year. I was hoping that one of you could take a look at this in the near future, as I have a feeling it could be effecting quite a few people without them really realising it. And more so as adoption of the latest Craft version picks up in January. I'd be very appreciative to hear any feedback. Thanks.

**Comment by sjcallender** [comment]
@jalendport - We just ran into a similar issue with this on the Annotated Notes plugins which caused serious content problems for our client. We have this plugin installed and haven't seen this issue popup, but we'd definitely feel much better if this PR could be merged sooner than later. What are you thinking, good sir?

**Comment by jakedohm** [comment]
@jalendport @monachilada's fork fixed the issue that I was seeing with Neo blocks being destroyed upon re-save 👍

For anyone following this, until this gets merged, you can patch it by using @monachilada's fork by doing the following:

1. Add the following to `composer.json`
```json
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/monachilada/craft-preparse-field"
  }
],
```
2. Update your `require` reference for `craft-preparse-field`

### Before
```json
"besteadfast/craft-preparse-field": "1.x.x"
```

## After
```json
"besteadfast/craft-preparse-field": "dev-develop"
```

**Comment by jalendport** [comment]
@monachilada thanks for the PR! Thanks everyone else for your patience; I’ve got some time set aside tomorrow afternoon to test ‘er out and then I’ll merge and cut a new release for y’all.

**Comment by sjcallender** [comment]
Hey @jalendport! How'd that testing go? 😉

**Comment by brandonkelly** [comment]
Thanks @jalendport! 🎉

**Comment by monachilada** [comment]
Thanks @jalendport

**Comment by sjcallender** [comment]
About time! Haha. I mean, thanks @jalendport! 😜

**Comment by gramirez22** [comment]
@monachilada are you able to provide the steps to recreate this issue? If possible please include the craft version. Unfortunately this broke when using globals. I'm having a hard time recreating the issue so I know for sure I'm missing a step (or version) in my setup. Thank you.

**Comment by gramirez22** [comment]
@jakedohm same question for you, please. Could you provide the steps and setup to recreate the issue? You mentioned you were using neo, are you able to provide the neo and craft versions? Thank you.

**Comment by gramirez22** [comment]
@monachilada, @jakedohm sorry guys I was able to reproduce the issue (of course right after I asked for descriptions of setup). I will be looking into this with @jalendport . Thank you.

**Pull request merged**
